### PR TITLE
[ENH] Possible solution for hanging sessions

### PR DESCRIPTION
**Pull request by anibalsolon**
When the program crashes, the VNC server do not get finished, because the container get stuck in the tail log.

A solution is to use `wait` to lock a script while a backgrounded app does not exit. Once the app quits, the `wait` will let the script continue, killing the VNC server.

Also, the whole XFCE is not required, just its window manager is enough.

### CODE REVIEW

**Review by soichih — COMMENTED** [review]
Thanks @anibalsolon ! 

Is there any way you can keep the original `test.sh` intact? Maybe you can create `test.local.sh` or somehow merge your change so it will work either on dev1 or localhost? 

I think the added benefit of just running the x-window-manager is that, you probably don't have to manually maximize the window with wmctrl. I had to install the full xfce for some App, however.. the icons and what not goesn't get installed and I was too lazy to pick and choose each ones.

**Comment by soichih** [comment]
By the way, I just tested it and the container seems to be terminated when I close down the fslview. So your update seems to work!

**Comment by anibalsolon** [comment]
> Is there any way you can keep the original `test.sh` intact? Maybe you can create `test.local.sh` or somehow merge your change so it will work either on dev1 or localhost?

Sure thing! I've reverted the test.sh.

Keeping only the WM still requires the maximizing/fullscreen via `wmctrl`. We can try to replicate this to other apps in a way works well for all.

**Comment by soichih** [comment]
@anibalsolon Yes, please apply this to other native UIs.

```
brainlfie/ui-fsleyes
brainlife/ui-dsistudio
brainlife/ui-fibernavigator
brainlife/ui-freeview
brainlife/ui-wb_view
brainlife/ui-itksnap
brainlife/ui-trackvis
brainlife/ui-html
brainlife/ui-microgl
brainlife/ui-brainstorm
brainlife/ui-mrview
brainlife/ui-conn
```

I think that's it..

**Pull request merged**
